# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-CustomErrorMessage
version:      0.02
version_from: lib/Catalyst/Plugin/CustomErrorMessage.pm
installdirs:  site
requires:
    Carp::Clan:                    0
    Class::Data::Inheritable:      0
    HTML::Entities:                0
    NEXT:                          0
    Test::More:                    0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
